import { Routes } from '@angular/router';
import { HomeComponent } from './Pages/home/home.component';
import { AboutComponent } from './Pages/about/about.component';
import { CareersComponent } from './Pages/careers/careers.component';
import { ContactComponent } from './Pages/contact/contact.component';
import { JobsComponent } from './Pages/jobs/jobs.component';
import { FeedbackComponent } from './Pages/feedback/feedback.component';
import { CommonQuestionsComponent } from './Pages/common-questions/common-questions.component';
import { PageNotFoundComponent } from './Pages/page-not-found/page-not-found.component';
import { QuestionComponent } from './Pages/question/question.component';
import { PaymentsMethodsAndTermsComponent } from './Pages/payments-methods-and-terms/payments-methods-and-terms.component';
import { ReturnOrEditProductComponent } from './Pages/return-or-edit-product/return-or-edit-product.component';
import { PrivacyPolicyComponent } from './Pages/privacy-policy/privacy-policy.component';
import { TaxCertificateComponent } from './Pages/tax-certificate/tax-certificate.component';
import { ECommerceAuthenticationCertificateComponent } from './Pages/e-commerce-authentication-certificate/e-commerce-authentication-certificate.component';
import { OrderPageComponent } from './Pages/order-page/order-page.component';
export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'about', component: AboutComponent },
    { path: 'careers', component: CareersComponent },
    { path: 'contact', component: ContactComponent },
    { path: 'jobs', component: JobsComponent },
    { path: 'feedback', component: FeedbackComponent },
    { path: 'commonQuestions/:id', component: QuestionComponent },
    { path: 'commonQuestions', component: CommonQuestionsComponent },
    { path: 'terms-and-payments', component: PaymentsMethodsAndTermsComponent },
    { path: 'return-edit-policy', component: ReturnOrEditProductComponent },
    { path: 'privacy-policy', component: PrivacyPolicyComponent },
    { path: 'tax-certificate', component: TaxCertificateComponent },
    { path: 'e-commerce-authentication', component: ECommerceAuthenticationCertificateComponent },
    { path: 'offer', component: OrderPageComponent },
    { path: '**', component: PageNotFoundComponent }
];
